#!/usr/bin/env python3
"""
Add Astribot logo to the UV texture of astribot_torso_link_4.

Post-processes the texture PNG generated by glb2uv_xatlas.py,
overlaying the logo at the correct chest position by mapping 3D
face positions through the OBJ UV layout.

The script identifies front-facing faces in the logo zone, computes
where each face maps in the logo texture, and paints the logo pixels
into the correct UV triangle positions in the OBJ texture.

Usage:
  python3 add_logo_to_texture.py
  python3 add_logo_to_texture.py --obj PATH --texture PATH --logo PATH
  python3 add_logo_to_texture.py --output /path/to/output.png

Defaults (relative to script directory):
  --obj      glb2uv/output_obj/astribot_torso_link_4.obj
  --texture  glb2uv/output_texture/astribot_torso_link_4.png
  --logo     logo_texture.png
  --output   overwrites --texture in-place
"""

import os
import sys
import argparse
import time
import numpy as np
from PIL import Image

from lib.constants import LOGO_Z_CENTER, LOGO_Y_CENTER, ZONE_HALF, FRONT_THRESHOLD
from lib.obj_io import parse_obj


def find_logo_faces(verts, faces):
    """Find faces in the logo zone based on 3D position and normal.

    Uses Z-up OBJ coordinates:
      X = front, Y = horizontal (-Z_glb), Z = up (Y_glb)

    Returns list of face indices in the logo zone.
    """
    print("  Finding logo zone faces...")
    t0 = time.time()
    logo_indices = []

    for i, (face_v, _) in enumerate(faces):
        if len(face_v) < 3:
            continue

        v0 = verts[face_v[0]]
        v1 = verts[face_v[1]]
        v2 = verts[face_v[2]]
        centroid = (v0 + v1 + v2) / 3.0

        e1 = v1 - v0
        e2 = v2 - v0
        fn = np.cross(e1, e2)
        mag = np.linalg.norm(fn)
        if mag < 1e-12:
            continue
        fn /= mag

        if (fn[0] > FRONT_THRESHOLD and
                abs(centroid[2] - LOGO_Z_CENTER) < ZONE_HALF and
                abs(centroid[1] - LOGO_Y_CENTER) < ZONE_HALF):
            logo_indices.append(i)

    dt = time.time() - t0
    print(f"  Found {len(logo_indices)} logo zone faces ({dt:.1f}s)")
    return logo_indices


def rasterize_logo(tex_arr, obj_uvs, faces, verts, logo_indices, logo_arr):
    """Paint logo pixels onto texture at logo zone face UV positions.

    For each face in the logo zone:
      1. Get the face's UV triangle in texture pixel space
      2. Compute "logo UV" for each vertex from its 3D position
      3. For each pixel inside the UV triangle, interpolate logo UV
         using barycentric coordinates and sample the logo image

    Returns:
        Number of pixels painted.
    """
    tex_h, tex_w = tex_arr.shape[:2]
    logo_h, logo_w = logo_arr.shape[:2]
    zone_span = ZONE_HALF * 2
    painted = 0

    print(f"  Rasterizing logo onto {tex_w}x{tex_h} texture "
          f"({len(logo_indices)} faces)...")
    t0 = time.time()

    for fi in logo_indices:
        face_v, face_vt = faces[fi]

        # --- OBJ UV triangle in pixel space ---
        uv0 = obj_uvs[face_vt[0]]
        uv1 = obj_uvs[face_vt[1]]
        uv2 = obj_uvs[face_vt[2]]

        sw = tex_w - 1
        sh = tex_h - 1
        a = np.array([uv0[0] * sw, (1 - uv0[1]) * sh])
        b = np.array([uv1[0] * sw, (1 - uv1[1]) * sh])
        c = np.array([uv2[0] * sw, (1 - uv2[1]) * sh])

        # --- Logo UV for each vertex (from 3D position) ---
        p0 = verts[face_v[0]]
        p1 = verts[face_v[1]]
        p2 = verts[face_v[2]]

        lu0 = 0.5 - p0[1] / zone_span
        lv0 = 0.5 + (p0[2] - LOGO_Z_CENTER) / zone_span
        lu1 = 0.5 - p1[1] / zone_span
        lv1 = 0.5 + (p1[2] - LOGO_Z_CENTER) / zone_span
        lu2 = 0.5 - p2[1] / zone_span
        lv2 = 0.5 + (p2[2] - LOGO_Z_CENTER) / zone_span

        # --- Bounding box ---
        min_x = max(0, int(min(a[0], b[0], c[0])))
        max_x = min(tex_w - 1, int(max(a[0], b[0], c[0])) + 1)
        min_y = max(0, int(min(a[1], b[1], c[1])))
        max_y = min(tex_h - 1, int(max(a[1], b[1], c[1])) + 1)

        if min_x > max_x or min_y > max_y:
            continue

        # --- Barycentric precompute ---
        v0 = b - a
        v1 = c - a
        d00 = v0[0] * v0[0] + v0[1] * v0[1]
        d01 = v0[0] * v1[0] + v0[1] * v1[1]
        d11 = v1[0] * v1[0] + v1[1] * v1[1]
        denom = d00 * d11 - d01 * d01
        if abs(denom) < 1e-10:
            continue
        inv_denom = 1.0 / denom

        # --- Rasterize pixels ---
        for py in range(min_y, max_y + 1):
            for px in range(min_x, max_x + 1):
                dx = px - a[0]
                dy = py - a[1]
                d20 = dx * v0[0] + dy * v0[1]
                d21 = dx * v1[0] + dy * v1[1]

                bary_b = (d11 * d20 - d01 * d21) * inv_denom
                bary_c = (d00 * d21 - d01 * d20) * inv_denom
                bary_a = 1.0 - bary_b - bary_c

                if bary_a >= -0.001 and bary_b >= -0.001 and bary_c >= -0.001:
                    lu = bary_a * lu0 + bary_b * lu1 + bary_c * lu2
                    lv = bary_a * lv0 + bary_b * lv1 + bary_c * lv2

                    lx = int(np.clip(lu * (logo_w - 1), 0, logo_w - 1))
                    ly = int(np.clip((1 - lv) * (logo_h - 1), 0, logo_h - 1))

                    tex_arr[py, px] = logo_arr[ly, lx]
                    painted += 1

    dt = time.time() - t0
    print(f"  Painted {painted} pixels ({dt:.1f}s)")
    return painted


def main():
    parser = argparse.ArgumentParser(
        description="Add Astribot logo to OBJ UV texture")
    parser.add_argument("--obj", default=None,
                        help="OBJ file path (default: glb2uv/output_obj/"
                             "astribot_torso_link_4.obj)")
    parser.add_argument("--texture", default=None,
                        help="Input texture PNG (default: glb2uv/output_texture/"
                             "astribot_torso_link_4.png)")
    parser.add_argument("--logo", default=None,
                        help="Logo texture PNG (default: logo_texture.png)")
    parser.add_argument("--output", default=None,
                        help="Output texture path (default: overwrite --texture)")
    parser.add_argument("--flip-logo", action="store_true",
                        help="Flip logo texture vertically before sampling "
                             "(use if logo appears upside-down)")
    args = parser.parse_args()

    base_dir = os.path.dirname(os.path.abspath(__file__))
    obj_path = args.obj or os.path.join(
        base_dir, "glb2uv", "output_obj", "astribot_torso_link_4.obj")
    tex_path = args.texture or os.path.join(
        base_dir, "glb2uv", "output_texture", "astribot_torso_link_4.png")
    logo_path = args.logo or os.path.join(base_dir, "logo_texture.png")
    output_path = args.output or tex_path

    for path, label in [(obj_path, "OBJ"), (tex_path, "Texture"),
                         (logo_path, "Logo")]:
        if not os.path.exists(path):
            print(f"ERROR: {label} not found: {path}")
            sys.exit(1)

    print(f"OBJ:     {obj_path}")
    print(f"Texture: {tex_path}")
    print(f"Logo:    {logo_path}")
    print(f"Output:  {output_path}")

    # Step 1: Parse OBJ
    print(f"  Parsing OBJ: {os.path.basename(obj_path)} ...")
    t0 = time.time()
    verts, uvs, _normals, faces = parse_obj(obj_path)
    dt = time.time() - t0
    print(f"  Parsed: {len(verts)} verts, {len(uvs)} UVs, "
          f"{len(faces)} faces ({dt:.1f}s)")

    # Step 2: Find logo zone faces
    logo_indices = find_logo_faces(verts, faces)
    if not logo_indices:
        print("WARNING: No faces found in logo zone. Check coordinate system.")
        sys.exit(1)

    # Step 3: Load images
    tex_img = Image.open(tex_path).convert('RGB')
    tex_arr = np.array(tex_img)
    print(f"  Texture: {tex_img.size[0]}x{tex_img.size[1]}")

    logo_img = Image.open(logo_path).convert('RGB')
    if args.flip_logo:
        logo_img = logo_img.transpose(Image.FLIP_TOP_BOTTOM)
        print("  Logo flipped vertically")
    logo_arr = np.array(logo_img)
    print(f"  Logo:    {logo_img.size[0]}x{logo_img.size[1]}")

    # Step 4: Rasterize logo onto texture
    n_painted = rasterize_logo(tex_arr, uvs, faces, verts,
                               logo_indices, logo_arr)

    if n_painted == 0:
        print("WARNING: No pixels painted. The logo zone faces may not "
              "overlap with valid UV regions.")
        sys.exit(1)

    # Step 5: Save
    result = Image.fromarray(tex_arr)
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    result.save(output_path)
    print(f"\nSaved: {output_path}")

    proj_tex = os.path.expanduser(
        "~/ros2/simu/astribot_simulation/astribot_descriptions/"
        "urdf/astribot_s1_urdf/meshes/textures/")
    print(f"\nTo apply to simulation:")
    print(f"  cp {output_path} {proj_tex}")


if __name__ == "__main__":
    main()
