"""OBJ file reading and writing utilities."""

import os
import numpy as np


def parse_obj(filepath):
    """Parse OBJ file for vertices, UVs, normals, and face indices.

    Returns:
        verts:   (N, 3) float64 array of vertex positions
        uvs:     (M, 2) float64 array of UV coordinates (empty if none)
        normals: (K, 3) float64 array of normals (empty if none)
        faces:   list of (vert_indices[3], uv_indices[3]) tuples
                 (uv_indices fall back to vert_indices when absent)
    """
    verts = []
    uvs = []
    normals = []
    faces = []

    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('v '):
                parts = line.split()
                verts.append((float(parts[1]), float(parts[2]), float(parts[3])))
            elif line.startswith('vt '):
                parts = line.split()
                uvs.append((float(parts[1]), float(parts[2])))
            elif line.startswith('vn '):
                parts = line.split()
                normals.append((float(parts[1]), float(parts[2]), float(parts[3])))
            elif line.startswith('f '):
                parts = line.split()
                face_v, face_vt = [], []
                for p in parts[1:4]:  # triangles only
                    indices = p.split('/')
                    face_v.append(int(indices[0]) - 1)
                    if len(indices) >= 2 and indices[1]:
                        face_vt.append(int(indices[1]) - 1)
                    else:
                        face_vt.append(int(indices[0]) - 1)
                faces.append((face_v, face_vt))

    return (np.array(verts, dtype=np.float64),
            np.array(uvs, dtype=np.float64) if uvs else np.empty((0, 2), dtype=np.float64),
            np.array(normals, dtype=np.float64) if normals else np.empty((0, 3), dtype=np.float64),
            faces)


def parse_colored_obj(filepath):
    """Parse OBJ with vertex colors (v x y z r g b).

    Returns:
        positions: (N, 3) float64
        colors:    (N, 3) float64 (default white if absent)
        normals:   (K, 3) float64 or None
        faces:     list of (vert_indices[], normal_indices[]) tuples
        has_colors: bool
    """
    positions = []
    colors = []
    normals = []
    faces = []
    has_colors = False

    with open(filepath, 'r') as f:
        for line in f:
            if line.startswith('v ') and not line.startswith('vt') and not line.startswith('vn'):
                parts = line.strip().split()
                positions.append([float(parts[1]), float(parts[2]), float(parts[3])])
                if len(parts) >= 7:
                    colors.append([float(parts[4]), float(parts[5]), float(parts[6])])
                    has_colors = True
                else:
                    colors.append([0.97, 0.97, 0.98])
            elif line.startswith('vn '):
                parts = line.strip().split()
                normals.append([float(parts[1]), float(parts[2]), float(parts[3])])
            elif line.startswith('f '):
                parts = line.strip().split()[1:]
                face_v = []
                face_vn = []
                for p in parts:
                    indices = p.split('/')
                    face_v.append(int(indices[0]) - 1)
                    if len(indices) >= 3 and indices[2]:
                        face_vn.append(int(indices[2]) - 1)
                    else:
                        face_vn.append(int(indices[0]) - 1)
                faces.append((face_v, face_vn))

    return (np.array(positions), np.array(colors),
            np.array(normals) if normals else None,
            faces, has_colors)


def write_obj(filepath, verts, faces, normals, uvs):
    """Write OBJ file with UV coordinates and normals."""
    with open(filepath, 'w') as f:
        f.write("# Generated by mesh processing toolkit\n")
        for v in verts:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for uv in uvs:
            f.write(f"vt {uv[0]:.8f} {uv[1]:.8f}\n")
        for n in normals:
            f.write(f"vn {n[0]:.8f} {n[1]:.8f} {n[2]:.8f}\n")
        for face in faces:
            i0, i1, i2 = face[0] + 1, face[1] + 1, face[2] + 1
            f.write(f"f {i0}/{i0}/{i0} {i1}/{i1}/{i1} {i2}/{i2}/{i2}\n")


def find_color_obj(mesh_name, search_dir):
    """Find a colored OBJ file in search_dir.

    MeshLab exports with '_color' suffix and sometimes inconsistent spacing.
    """
    exact = os.path.join(search_dir, f"{mesh_name}.obj")
    if os.path.exists(exact):
        return exact

    for p in [f"{mesh_name}_color.obj", f"{mesh_name} _color.obj"]:
        path = os.path.join(search_dir, p)
        if os.path.exists(path):
            return path

    if os.path.exists(search_dir):
        for f in os.listdir(search_dir):
            if f.endswith('.obj') and mesh_name in f:
                return os.path.join(search_dir, f)
    return None
